name: the-awkward-photographer
favicon: null
layout_spectrum: 0
typography_spectrum: 0.75385
title: The awkward photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefdfe'
    - '#141316'
    - '#4e4c51'
    - '#c3c2c5'
    - '#8c8a8f'
  brandStrength: 0.5
  lightness: 0.617120900657028
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
