name: the-awkward-photographer
favicon: null
layout_spectrum: 0.15207607904449105
typography_spectrum: 0.8974730067420751
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2625369664747268
  lightness: 0.617120900657028
  saturation: 0.5872716903686523
  rhythmicContrast: 0.5579879134893417
purpose: []
