name: the-awkward-photographer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75385
title: The awkward photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#769dcd'
    - '#d0d8e1'
    - '#253953'
    - '#60625f'
  brandStrength: 0
  lightness: 0.617120900657028
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
